install.packages("ggplot2")
install.packages("dplyr")
install.packages("RColorBrewer")
install.packages("ggrepel")
install.packages("ggthemes")
install.packages("xkcd")
install.packages("extrafont")

library(extrafont)
download.file("http://simonsoftware.se/other/xkcd.ttf", dest="xkcd.ttf", mode="wb")
system("mkdir ~/.fonts")
system("cp xkcd.ttf ~/.fonts")
font_import(paths='~/.fonts', pattern = "[X/x]kcd", prompt=FALSE)
fonts()
fonttable()
loadfonts()
